blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""defines URL patters for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    #Page for adding a new blog
    path('new_blog/', views.new_blog, name="new_blog"),
    #Page for editing a blog
    path('edit_blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    #  Registration page
    path('register/', views.register, name="register"),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    '''A blog'''
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        '''Return a string representation of the model.'''
        return self.title

    def __str__(self):
        '''Return a string representation of the model.'''    
        if len(self.text) > 50:
            return self.text[:50] + '...'
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Title', 'text': 'Entry'} # to add lables to input box fill in blank strings
        

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import BlogPost
from .forms import BlogForm

# Create your views here.
def index(request):
    '''The home page for blog and shows all posts'''
    posts = BlogPost.objects.order_by('-date_added')
    context = {'posts': posts}
    return render(request, 'blogs/index.html', context)

@login_required
def new_blog(request):
    """Add a new blog"""
    if request.method != 'POST':
        #No data submitted, create blank form
        form = BlogForm()
    else:
        # POST data received, process data
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blogs:index')

    #display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

@login_required
def edit_blog(request, blog_id):
    """Edit existing blog"""
    blog = BlogPost.objects.get(id=blog_id)

    check_post_owner(blog, request)

    if request.method != 'POST':
        # Inital request; prefill form with current post
        form = BlogForm(instance=blog)
    else:
        # POST data submitted; process data
        form = BlogForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')  #Could be wrong but we'll see!
            
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blog.html', context)

def check_post_owner(blog, request):
    if blog.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the new user in and redirect them to the home page
            login(request, new_user)
            return redirect('blogs:index')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Learning Log</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'blogs:index'%}">
      Blogs
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse"
      aria-expanded="false" aria-label="Toggle navigation"> 
    <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="navbar-text">Hello, {{ user.username }}</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>
</html>

blogs/templates/blogs/edit_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block pageheader %}
    <h2>Edit Post</h2>
{% endblock pageheader %}

{% block content %}
    <form action="{% url 'blogs:edit_blog' blog.id %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Save Changes</button>
        {% endbuttons %}
    </form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block pageheader %}
    <h3>Posts</h3>
{% endblock pageheader %}


{% block content%}
    <p>
        <a href="{% url 'blogs:new_blog' %}">Add a new post:</a>
    </p>
    {% for post in posts %}
    <div class="card mb-3">
        <h4 class="card-header">
            {{ post.title }}
            <small>
                {{ post.date_added|date:'M d, Y H:i' }}
                {{ post.owner }}
            </small>
        </h4>
        <div class="card-body">
            {{ post.text|linebreaks }}
            <small>
                <a href="{% url 'blogs:edit_blog' post.id %}">edit post</a>
            </small>
        </div>
    </div>
    {% empty %}
        <li>No posts have been added yet.</li>
    {% endfor %}

{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block pageheader %}
    <h2>New Blog</h2>
{% endblock pageheader %}


{% block content %}
    <form action="{% url 'blogs:new_blog' %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add post</button>
        {% endbuttons %}

    </form>

{% endblock content %}